import { Injectable, ErrorHandler } from "@angular/core";

const AllTimeZones = {
    "Africa" : [
        "Abidjan",
        "Accra",
        "Addis Ababa",
        "Algiers",
        "Asmara",
        "Asmera",
        "Bamako",
        "Bangui",
        "Banjul",
        "Bissau",
        "Blantyre",
        "Brazzaville",
        "Bujumbura",
        "Cairo",
        "Casablanca",
        "Ceuta",
        "Conakry",
        "Dakar",
        "Dar es Salaam",
        "Djibouti",
        "Douala",
        "El Aaiun",
        "Freetown",
        "Gaborone",
        "Harare",
        "Johannesburg",
        "Juba",
        "Kampala",
        "Khartoum",
        "Kigali",
        "Kinshasa",
        "Lagos",
        "Libreville",
        "Lome",
        "Luanda",
        "Lubumbashi",
        "Lusaka",
        "Malabo",
        "Maputo",
        "Maseru",
        "Mbabane",
        "Mogadishu",
        "Monrovia",
        "Nairobi",
        "Ndjamena",
        "Niamey",
        "Nouakchott",
        "Ouagadougou",
        "Porto",
        "Sao Tome",
        "Timbuktu",
        "Tripoli",
        "Tunis",
        "Windhoek"
    ],
    "America" : [
        "Adak",
        "Anchorage",
        "Anguilla",
        "Antigua",
        "Araguaina",
        "Buenos Aires, Argentina",
        "Catamarca, Argentina",
        "Comod Rivadavia, Argentina",
        "Cordoba, Argentina",
        "Jujuy, Argentina",
        "La Rioja, Argentina",
        "Mendoza, Argentina",
        "Rio Gallegos, Argentina",
        "Salta, Argentina",
        "San Juan, Argentina",
        "San Luis, Argentina",
        "Tucuman, Argentina",
        "Ushuaia, Argentina",
        "Aruba",
        "Asuncion",
        "Atikokan",
        "Atka",
        "Bahia",
        "Bahia Banderas",
        "Barbados",
        "Belem",
        "Belize",
        "Blanc",
        "Boa Vista",
        "Bogota",
        "Boise",
        "Buenos Aires",
        "Cambridge Bay",
        "Campo Grande",
        "Cancun",
        "Caracas",
        "Catamarca",
        "Cayenne",
        "Cayman",
        "Chicago",
        "Chihuahua",
        "Coral Harbour",
        "Cordoba",
        "Costa Rica",
        "Creston",
        "Cuiaba",
        "Curacao",
        "Danmarkshavn",
        "Dawson",
        "Dawson Creek",
        "Denver",
        "Detroit",
        "Dominica",
        "Edmonton",
        "Eirunepe",
        "El Salvador",
        "Ensenada",
        "Fort Nelson",
        "Fort Wayne",
        "Fortaleza",
        "Glace Bay",
        "Godthab",
        "Goose Bay",
        "Grand Turk",
        "Grenada",
        "Guadeloupe",
        "Guatemala",
        "Guayaquil",
        "Guyana",
        "Halifax",
        "Havana",
        "Hermosillo",
        "Indianapolis, Indiana",
        "Knox, Indiana",
        "Marengo, Indiana",
        "Petersburg, Indiana",
        "Tell City, Indiana",
        "Vevay, Indiana",
        "Vincennes, Indiana",
        "Winamac, Indiana",
        "Indianapolis",
        "Inuvik",
        "Iqaluit",
        "Jamaica",
        "Jujuy",
        "Juneau",
        "Louisville, Kentucky",
        "Monticello, Kentucky",
        "Knox I'N",
        "Kralendijk",
        "La Paz",
        "Lima",
        "Los Angeles",
        "Louisville",
        "Lower Princes",
        "Maceio",
        "Managua",
        "Manaus",
        "Marigot",
        "Martinique",
        "Matamoros",
        "Mazatlan",
        "Mendoza",
        "Menominee",
        "Merida",
        "Metlakatla",
        "Mexico City",
        "Miquelon",
        "Moncton",
        "Monterrey",
        "Montevideo",
        "Montreal",
        "Montserrat",
        "Nassau",
        "New York",
        "Nipigon",
        "Nome",
        "Noronha",
        "Beulah, North Dakota",
        "Center, North Dakota",
        "New Salem, North Dakota",
        "Ojinaga",
        "Panama",
        "Pangnirtung",
        "Paramaribo",
        "Phoenix",
        "Port",
        "Port of Spain",
        "Porto Acre",
        "Porto Velho",
        "Puerto Rico",
        "Punta Arenas",
        "Rainy River",
        "Rankin Inlet",
        "Recife",
        "Regina",
        "Resolute",
        "Rio Branco",
        "Rosario",
        "Santa Isabel",
        "Santarem",
        "Santiago",
        "Santo Domingo",
        "Sao Paulo",
        "Scoresbysund",
        "Shiprock",
        "Sitka",
        "St Barthelemy",
        "St Johns",
        "St Kitts",
        "St Lucia",
        "St Thomas",
        "St Vincent",
        "Swift Current",
        "Tegucigalpa",
        "Thule",
        "Thunder Bay",
        "Tijuana",
        "Toronto",
        "Tortola",
        "Vancouver",
        "Virgin",
        "Whitehorse",
        "Winnipeg",
        "Yakutat",
        "Yellowknife"
    ],
    "Antarctica" : [
        "Casey",
        "Davis",
        "Dumont D'Urville",
        "Macquarie",
        "Mawson",
        "McMurdo",
        "Palmer",
        "Rothera",
        "South Pole",
        "Syowa",
        "Troll",
        "Vostok"
    ],
    "Arctic" : [
        "Longyearbyen"
    ],
    "Asia" : [
        "Aden",
        "Almaty",
        "Amman",
        "Anadyr",
        "Aqtau",
        "Aqtobe",
        "Ashgabat",
        "Ashkhabad",
        "Atyrau",
        "Baghdad",
        "Bahrain",
        "Baku",
        "Bangkok",
        "Barnaul",
        "Beirut",
        "Bishkek",
        "Brunei",
        "Calcutta",
        "Chita",
        "Choibalsan",
        "Chongqing",
        "Chungking",
        "Colombo",
        "Dacca",
        "Damascus",
        "Dhaka",
        "Dili",
        "Dubai",
        "Dushanbe",
        "Famagusta",
        "Gaza",
        "Harbin",
        "Hebron",
        "Ho Chi Minh",
        "Hong Kong",
        "Hovd",
        "Irkutsk",
        "Istanbul",
        "Jakarta",
        "Jayapura",
        "Jerusalem",
        "Kabul",
        "Kamchatka",
        "Karachi",
        "Kashgar",
        "Kathmandu",
        "Katmandu",
        "Khandyga",
        "Kolkata",
        "Krasnoyarsk",
        "Kuala Lumpur",
        "Kuching",
        "Kuwait",
        "Macao",
        "Macau",
        "Magadan",
        "Makassar",
        "Manila",
        "Muscat",
        "Nicosia",
        "Novokuznetsk",
        "Novosibirsk",
        "Omsk",
        "Oral",
        "Phnom Penh",
        "Pontianak",
        "Pyongyang",
        "Qatar",
        "Qyzylorda",
        "Rangoon",
        "Riyadh",
        "Saigon",
        "Sakhalin",
        "Samarkand",
        "Seoul",
        "Shanghai",
        "Singapore",
        "Srednekolymsk",
        "Taipei",
        "Tashkent",
        "Tbilisi",
        "Tehran",
        "Tel Aviv",
        "Thimbu",
        "Thimphu",
        "Tokyo",
        "Tomsk",
        "Ujung Pandang",
        "Ulaanbaatar",
        "Ulan Bator",
        "Urumqi",
        "Ust",
        "Vientiane",
        "Vladivostok",
        "Yakutsk",
        "Yangon",
        "Yekaterinburg",
        "Yerevan"
    ],
    "Atlantic" : [
        "Azores",
        "Bermuda",
        "Canary",
        "Cape Verde",
        "Faeroe",
        "Faroe",
        "Jan Mayen",
        "Madeira",
        "Reykjavik",
        "South Georgia",
        "St Helena",
        "Stanley"
    ],
    "Australia" : [
        "ACT",
        "Adelaide",
        "Brisbane",
        "Broken Hill",
        "Canberra",
        "Currie",
        "Darwin",
        "Eucla",
        "Hobart",
        "LHI",
        "Lindeman",
        "Lord Howe",
        "Melbourne",
        "NSW",
        "North",
        "Perth",
        "Queensland",
        "South",
        "Sydney",
        "Tasmania",
        "Victoria",
        "West",
        "Yancowinna"
    ],
    "Brazil" : [
        "Acre",
        "De Noronha",
        "East",
        "West"
    ],
    "Canada" : [
        "Atlantic",
        "Central",
        "Eastern",
        "Mountain",
        "Newfoundland",
        "Pacific",
        "Saskatchewan",
        "Yukon"
    ],
    "Chile" : [
        "Continental",
        "Easter Island"
    ],
    "Cuba" : [
        "Cuba"
    ],
    "Egypt" : [
        "Egypt"
    ],
    "Eire" : [
        "Eire"
    ],
    "Etc" : [
        "GMT",
        "GMT+0",
        "GMT+1",
        "GMT+10",
        "GMT+11",
        "GMT+12",
        "GMT+2",
        "GMT+3",
        "GMT+4",
        "GMT+5",
        "GMT+6",
        "GMT+7",
        "GMT+8",
        "GMT+9",
        "GMT",
        "GMT",
        "GMT",
        "GMT",
        "GMT",
        "GMT",
        "GMT",
        "GMT",
        "GMT",
        "GMT",
        "GMT",
        "GMT",
        "GMT",
        "GMT",
        "GMT",
        "GMT0",
        "Greenwich",
        "UCT",
        "UTC",
        "Universal",
        "Zulu"
    ],
    "Europe" : [
        "Amsterdam",
        "Andorra",
        "Astrakhan",
        "Athens",
        "Belfast",
        "Belgrade",
        "Berlin",
        "Bratislava",
        "Brussels",
        "Bucharest",
        "Budapest",
        "Busingen",
        "Chisinau",
        "Copenhagen",
        "Dublin",
        "Gibraltar",
        "Guernsey",
        "Helsinki",
        "Isle of Man",
        "Istanbul",
        "Jersey",
        "Kaliningrad",
        "Kiev",
        "Kirov",
        "Lisbon",
        "Ljubljana",
        "London",
        "Luxembourg",
        "Madrid",
        "Malta",
        "Mariehamn",
        "Minsk",
        "Monaco",
        "Moscow",
        "Nicosia",
        "Oslo",
        "Paris",
        "Podgorica",
        "Prague",
        "Riga",
        "Rome",
        "Samara",
        "San Marino",
        "Sarajevo",
        "Saratov",
        "Simferopol",
        "Skopje",
        "Sofia",
        "Stockholm",
        "Tallinn",
        "Tirane",
        "Tiraspol",
        "Ulyanovsk",
        "Uzhgorod",
        "Vaduz",
        "Vatican",
        "Vienna",
        "Vilnius",
        "Volgograd",
        "Warsaw",
        "Zagreb",
        "Zaporozhye",
        "Zurich"
    ],
    "Hongkong" : [
        "Hongkong"
    ],
    "Iceland" : [
        "Iceland"
    ],
    "Indian" : [
        "Antananarivo",
        "Chagos",
        "Christmas",
        "Cocos",
        "Comoro",
        "Kerguelen",
        "Mahe",
        "Maldives",
        "Mauritius",
        "Mayotte",
        "Reunion"
    ],
    "Iran" : [
        "Iran"
    ],
    "Israel" : [
        "Israel"
    ],
    "Japan" : [
        "Japan"
    ],
    "Kwajalein" : [
        "Kwajalein"
    ],
    "Libya" : [
        "Libya"
    ],
    "Mexico" : [
        "Baja Norte",
        "Baja Sur",
        "General"
    ],
    "Navajo" : [
        "Navajo"
    ],
    "Pacific" : [
        "Apia",
        "Auckland",
        "Bougainville",
        "Chatham",
        "Chuuk",
        "Easter",
        "Efate",
        "Enderbury",
        "Fakaofo",
        "Fiji",
        "Funafuti",
        "Galapagos",
        "Gambier",
        "Guadalcanal",
        "Guam",
        "Honolulu",
        "Johnston",
        "Kiritimati",
        "Kosrae",
        "Kwajalein",
        "Majuro",
        "Marquesas",
        "Midway",
        "Nauru",
        "Niue",
        "Norfolk",
        "Noumea",
        "Pago Pago",
        "Palau",
        "Pitcairn",
        "Pohnpei",
        "Ponape",
        "Port Moresby",
        "Rarotonga",
        "Saipan",
        "Samoa",
        "Tahiti",
        "Tarawa",
        "Tongatapu",
        "Truk",
        "Wake",
        "Wallis",
        "Yap"
    ],
    "Poland" : [
        "Poland"
    ],
    "Portugal" : [
        "Portugal"
    ],
    "Turkey" : [
        "Turkey"
    ],
    "US" : [
        "Alaska",
        "Aleutian",
        "Arizona",
        "Central",
        "East",
        "Eastern",
        "Hawaii",
        "Indiana",
        "Michigan",
        "Mountain",
        "Pacific",
        "Pacific",
        "Samoa"
    ],

};


@Injectable()
export class TimezoneConstant {

    static getAllTimeZones() {
        return AllTimeZones;
    }

    static getTimeZone(key) {
        return AllTimeZones[key];
    }
}